repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.35.1'
    hooks:
      - id: yamllint
        files: .*values.*\.yaml$
        args:
          - "-s"
          - "-d"
          - "{extends: default, rules: {line-length: disable, comments-indentation: disable, document-start: disable}}"
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
      - id: helmlint
